# Generated by Django 5.2.4 on 2025-07-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_habit_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
