# Generated by Django 5.2.4 on 2025-07-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pomodorolog_pomodorosession'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodlog',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
